version: '3.5'
services:
  mongodb_container:
    image: mongo:5.0
    volumes:
      - mongodb_data_container:/data/db
    command: "--replSet rs0"
    restart: always

  replSetInit:
    image: mongo:5.0
    restart: on-failure
    depends_on:
      - mongodb_container
    links:
      - mongodb_container
    command:
      - /bin/sh
      - -c
      - |
        mongosh --host mongodb_container:27017 --eval 'rs.isMaster().ismaster || rs.initiate({
          "_id": "rs0",
          "members" : [
            { "_id" : 0, "host" : "mongodb_container:27017" }
          ]
        })'

  sync_server:
    image: quay.io/mongodb/tiered-sync-server:3a338e3155b92a1bf95ee4982542603ed0007e8d
    # quay.io/mongodb/tiered-sync-server:ecacaafc52b678f3adc7ad70f6188bdb88ab968c
    # linux/amd image: quay.io/mongodb/tiered-sync-server:3a338e3155b92a1bf95ee4982542603ed0007e8d
    # platform: linux/arm64/v8
    depends_on:
      - mongodb_container
      - replSetInit
    links:
      - mongodb_container
    volumes:
      - ./build/edge_config.json:/apps/configs/edge_config.json
    environment:
      EDGE_CONFIG_FILE: /apps/configs/edge_config.json
    ports:
      - 80:80
      - 27021:27021
    restart: always

volumes:
  mongodb_data_container:
